package App;

import engine.AudioDirectory;
import engine.FpSoundEngine;

import javafx.application.Application;
import javafx.collections.FXCollections;
import javafx.geometry.Insets;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ListView;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import setup.FormatService;
import setup.LineService;
import setup.MixerService;

import java.io.File;
import java.nio.file.Paths;
import java.util.ArrayList;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class TestArray extends Application {

    private AudioDirectory ad;
    private FpSoundEngine soundEngine;
    private File selectedAudio;

    public TestArray() {
        MixerService.MixerDetails(MixerService.SystemMixers()).forEach(System.out::println);
        System.out.println("---------------------------------------------------------------");
        LineService.SystemSourceDataLine(FormatService.PREFERRED_FORMAT).ifPresent(line -> System.out.println(LineService.LineDetails(line)));

        ad = new AudioDirectory(Paths.get(System.getProperty("user.home"), "/fpAudio/Test"));
        this.soundEngine = new FpSoundEngine();
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        primaryStage.setTitle("fp-sound Test");

        VBox root = new VBox();
        root.setPadding(new Insets(5,5,5,5));
        ListView<String> list = new ListView<String>();

        ArrayList<String> items = new ArrayList<>();
        ad.keys().sorted().forEach( items::add );
        list.setItems(FXCollections.observableArrayList(items));

        list.getSelectionModel().selectedItemProperty().addListener( (ov, old_val, new_val) -> {
            ad.get(new_val).ifPresent( audio -> {
                selectedAudio = audio;
            });
        } );

        list.setOnMouseClicked( event -> {
            if (event.getClickCount() == 2) {
                soundEngine.PlaySound(selectedAudio);
            }
        });

        root.getChildren().add(list);

        Button play = new Button("Play");
        play.setOnMouseClicked( event -> soundEngine.PlaySound(selectedAudio) );
        root.getChildren().add(play);

        primaryStage.setScene(new Scene(root, 400, 200));
        primaryStage.show();
    }

    @Override
    public void stop() {
        this.soundEngine.shutDownEngine();
    }

}
