package App;

import engine.AudioDirectory;
import engine.FpSoundEngine;

import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.geometry.Insets;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.GridPane;
import javafx.stage.Stage;
import setup.FormatService;
import setup.LineService;
import setup.MixerService;

import java.nio.file.NoSuchFileException;
import java.nio.file.Paths;
import java.util.concurrent.atomic.AtomicInteger;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class TestArray extends Application {

    private AudioDirectory ad;

    public TestArray() {
        MixerService.MixerDetails(MixerService.SystemMixers()).forEach(System.out::println);
        System.out.println("---------------------------------------------------------------");
        LineService.SystemSourceDataLine(FormatService.PREFERRED_FORMAT).ifPresent(line -> System.out.println(LineService.LineDetails(line)));

        ad = new AudioDirectory(Paths.get(System.getProperty("user.home"), "/fpAudio/Test"));
    }

    @Override
    public void start(Stage primaryStage) throws Exception {

        primaryStage.setTitle("fp-sound Test");
        Group root = new Group();

        GridPane grid = new GridPane();
        grid.setHgap(5);
        grid.setVgap(5);
        grid.setPadding(new Insets(5,5,5,5));

        root.getChildren().add(grid);
        AtomicInteger i = new AtomicInteger();
        ad.keys().forEach( key -> {
            ad.get(key).ifPresent( audio -> {
                Button b = new Button(key);
                b.setOnAction(new EventHandler<ActionEvent>() {
                    @Override public void handle(ActionEvent e) {
                        FpSoundEngine.PlaySound(audio);
                    }
                });
                i.getAndIncrement();
                grid.add(b, i.get()%5, i.get()/5);
            });
        });

        primaryStage.setScene(new Scene(root));
        primaryStage.show();
    }
}
