import engine.FpSoundEngine;

import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;
import setup.FormatService;
import setup.LineService;
import setup.MixerService;

import java.nio.file.Paths;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App extends Application {

    private Button play;

    public App() {
        MixerService.MixerDetails(MixerService.SystemMixers()).forEach(System.out::println);
        System.out.println("---------------------------------------------------------------");
        LineService.SystemSourceDataLine(FormatService.PREFERRED_FORMAT).ifPresent(line -> System.out.println(LineService.LineDetails(line)));
    }

    @Override
    public void start(Stage primaryStage) throws Exception {

        primaryStage.setTitle("fp-sound Test");
        Group root = new Group();

        play = new Button("play");
        play.setOnAction(new EventHandler<ActionEvent>() {
            @Override public void handle(ActionEvent e) {
                FpSoundEngine.PlaySound(Paths.get(System.getProperty("user.home"),"/fpAudio/test.wav").toFile());
            }
        });

        root.getChildren().add(play);

        primaryStage.setScene(new Scene(root));
        primaryStage.show();
    }
}
